endpoints:
   api:
      enabled: true
logging:
   level:
      root: info
ontimize:
   corsfilter:
      enabled: true
   globalcors:
      corsConfigurations:
         '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            exposedHeaders: ["X-Auth-Token","Content-disposition","X-Requested-With"]
            allowedMethods:
            - GET
            - POST
            - PUT
            - OPTIONS
            - DELETE
   jdbc:
      nameConvention: lower
      sqlhandler: postgres
      sqlConditionProcessor:
         uppperString: true
         upperLike: true
   security:
      mode: default
      roleInformationService:
         roleRepository: UserRoleDao
         roleNameColumn: rolename
         serverPermissionQueryId: serverPermissions
         serverPermissionNameColumn: PERMISSION_NAME
         clientPermissionQueryId: clientPermissions
         clientPermissionColumn: XMLCLIENTPERMISSION
      userInformationService:
         userRepository: UserDao
         userLoginColumn: nick_user
         userPasswordColumn: password_user
         queryId: login
         otherData:
            - id_user
            - name_user
            - surname_user
            - email_user
            - birthdate_user
            - create_date_user
            - delete_date_user
      userRoleInformationService:
         userRoleRepository: UserRoleDao
         queryId: userRole
         roleLoginColumn: nick_user
         roleNameColumn: ROLENAME
server:
   port: 33334
   tomcat:
      uri-encoding: UTF-8
   compression:
      enabled: true
      mime-types: application/json, application/xml
spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://45.84.210.174:65432/cd09
      username: cd09
      password: cd09_P4$$!
      initialSize: 10
      testOnBorrow: true
   main:
      banner-mode: 'off'
   session:
      store-type: none
   autoconfigure:
      exclude: |
         org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration
